site_name: Python Poetry Template
site_description: A template for dockerized python projects with poetry for dependency management
site_author: Author Name
edit_uri: edit/main/docs/
repo_name: pypoetry_template
repo_url: https://github.com/pvanberg/python-poetry-template
copyright: Maintained by <a href="author@mail.com">Author Name</a>.

nav:
  - Home: 
    - Introduction: index.md
    - Workflows: workflows.md
    - MkDocs: mkdocs.md
    - Container registry: registry.md
    - Dependabot: dependabot.md
  - Project structure: structure.md
  - Reference: reference/
plugins:
  - search
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
  - gen-files:
      scripts:
        - docs/gen_reference_pages.py
  - mkdocstrings:
      watch:
        - src/pypoetry_template

theme:
  logo: assets/project_logo.png
  favicon: assets/project_logo.png
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false
